<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Angies" ignored="0" name="Sign Up Fail" tests="1" failures="1" timestamp="08 Apr 2019 19:37:03 GMT" time="23.287" errors="0">
  <testcase name="testToDo" time="13.304" classname="suite.UAT_Sign_Up_Fail_Test">
    <failure type="java.lang.AssertionError" message="expected [There was an error looking up your email address!] but found [There was an error looking up your email address]">
      <![CDATA[java.lang.AssertionError: expected [There was an error looking up your email address!] but found [There was an error looking up your email address]
at suite.UAT_Sign_Up_Fail_Test.testToDo(UAT_Sign_Up_Fail_Test.java:97)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testToDo -->
</testsuite> <!-- Sign Up Fail -->
